-- if type(cmd) == "string" then
--     if cmd:sub(1, 3) == "PI=" then
--         local hex = cmd:sub(7)
--         local pi = tonumber(hex, 16)
--         if (pi & 0xf000) == 0 then return "-" end
--         if pi then
--             set_rds_pi(pi)
--             return "+"
--         end
--     end
-- end